server:
  port: 8081
# dubbo 配置
dubbo:
  application:
    id: dubbo-consumer
    name: dubbo-consumer
    qos-port: 33333
  # dubbo 注册中心地址
  registry:
    address: zookeeper://localhost:2181
  # 服务提供者的协议名和端口
  protocol:
    name: dubbo
    port: 28848
  consumer:
    timeout: 20000